### PR TITLE
Update to Swift 4

### PR DESCRIPTION
**Pull request by shirakaba**
The macOS framework (and the iOS, I'd expect too) now builds for Swift 4; it seemed to be all in Swift 3.3 despite the naming of the branch.

No updates merged from upstream; just a Swift version update.

### CODE REVIEW

**Comment by Fab1n** [comment]
The naming of the branch is in reference to the version number of the project where we based the mac changes on

**Comment by shirakaba** [comment]
Ah, that explains things.

**Comment by LukasGram** [comment]
We rebased onto version 5.0.0 of the original project. This included all Swift 4 changes from them as well as yours. So we now have a new branch: macOSBasedOn5.0.0
Thanks for your help!

**Comment by shirakaba** [comment]
Thank you; I'll be using this!

**Pull request closed without merging**
